INSERT INTO `products` (`pID`, `pCatID`, `pName`, `pImage`, `pDesc`) VALUES
(1, 1, 'Kitchen Design 1', 'kitchen 01.png', 'Kitchen Decor '),
(2, 1, 'Kitchen Design 2', 'kitchen 02.png', 'Best Kitchen Design'),
(3, 1, 'Kitchen Design 3', 'kitchen 03.png', 'Kitchen Worth Watching'),
(4, 1, 'Kitchen Design 4', 'kitchen 04.png', 'Award - Winning Kitchen Design'),
(5, 1, 'Kitchen Design 5', 'kitchen 05.png', 'Italian Design'),
(6, 2, 'Bedroom Design 1', 'bedroom 01.png', 'Best Bedroom Ever'),
(7, 2, 'Bedroom Design 2', 'bedroom 02.png', 'Best Bedroom Design Ever'),
(8, 2, 'Bedroom Design 3', 'bedroom 03.png', 'Best Bedroom Design Ever'),
(9, 2, 'Bedroom Design 4', 'bedroom 04.png', 'Best Bedroom ever'),
(10, 2, 'Bedroom Design 5', 'bedroom 05.png', 'Best Bedroom Ever'),
(11, 2, 'Bedroom Design 6', 'bedroom 06.png', 'Best Bedroom Ever'),
(12, 2, 'Bedroom Design 7', 'bedroom 07.png', 'Best Bedroom Ever'),
(13, 3, 'Office Design 1', 'office-1.png', 'Wow, What a office!!!!!'),
(14, 3, 'Office Design 2', 'office-2.png', 'Wow, What a office!!!!!'),
(15, 3, 'Office Design 3', 'office-3.png', 'Wow, What a office!!!!!'),
(16, 3, 'Office Design 4', 'office-4.png', 'Wow, What a office!!!!!'),
(17, 4, 'Chair 1', 'chair 01.png', 'Wow, What a chair!!!!!'),
(18, 4, 'Chair 2', 'chair 02.png', 'Wow, What a chair!!!!!'),
(19, 4, 'Chair 3', 'chair 03.png', 'Wow, What a chair!!!!!'),
(20, 4, 'Chair 4', 'chair 04.png', 'Wow, What a chair!!!!!'),
(21, 4, 'Chair 5', 'chair 05.png', 'Wow, What a chair!!!!!'),
(22, 5, 'Dining Table 1', 'dt 01.png', 'Wow, What a Table!!!!!'),
(23, 5, 'Dining Table 2', 'dt 02.png', 'Wow, What a Table!!!!!'),
(24, 5, 'Dining Table 3', 'dt 03.png', 'Wow, What a Table!!!!!'),
(25, 5, 'Dining Table 4', 'dt 04.png', 'Wow, What a Table!!!!!');